import { describe, it, expect } from 'vitest';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { SEED_ENEMIES } from '../../data/combat/enemyDefinitions';
import { SEED_ELITE_AFFIXES } from '../../data/combat/eliteAffixes';
import { SEED_ELEMENT_REACTIONS } from '../../data/combat/elementReactions';
import { enemyHpMult } from './difficulty';
import { STAGE_ENEMY_SPAWN_GROUPS } from '../../data/encounters/stageEnemyPacks';
import { SEED_ZONE_SEGMENTS } from '../../data/game/advancedMissionZones';

// Combat-balance MEASUREMENT harness (no balance constants are changed here — see docs/combat_balance_report.md).
// It computes effective-HP / TTK / affix / objective-timer tables straight from the real seed data + difficulty
// functions, asserts loose sanity bounds (so it guards regressions), and writes the report markdown so the
// numbers a human tunes from never drift from the code.

// Reference sustained player DPS used purely to turn HP into a comparable "time-to-kill". NOT a balance knob —
// just a yardstick (a mid hero basic-attack loop lands ~35–45 dmg/s). Tune by feel on a real GPU session.
const REFERENCE_DPS = 40;

const baseEffectiveHp = (maxHp: number, maxShield = 0) => maxHp + maxShield;
// Mirrors EliteAffixRuntime: hpMult applies first, then shield = round(boostedMaxHp × shieldFraction) (or flat addShield).
const affixEffectiveHp = (maxHp: number, maxShield = 0, a?: { hpMult?: number; addShield?: number; shieldFraction?: number }) => {
  const boostedHp = maxHp * (a?.hpMult ?? 1);
  const shield = a?.shieldFraction ? Math.round(boostedHp * a.shieldFraction) : (a?.addShield ?? 0);
  return boostedHp + maxShield + shield;
};
const ttk = (effHp: number) => Math.ceil(effHp / REFERENCE_DPS);

const nonBoss = SEED_ENEMIES.filter((e) => !e.isBoss);

// --- Affix density per zone (measured from the actual applied policies, not the source const). ---
const zoneDensity: Record<string, number> = {};
for (const g of STAGE_ENEMY_SPAWN_GROUPS) {
  if (!g.affixPolicy) continue;
  zoneDensity[g.zoneId] = Math.max(zoneDensity[g.zoneId] ?? 0, g.affixPolicy.chancePerEnemy);
}

// --- Objective timers across all segments. ---
interface TimerRow { segmentId: string; type: string; seconds: number }
const timers: TimerRow[] = [];
for (const seg of SEED_ZONE_SEGMENTS) {
  for (const c of seg.completionConditions) {
    if (c.type === 'survive-timer' || c.type === 'hold-zone') timers.push({ segmentId: seg.id, type: c.type, seconds: c.seconds });
    else if (c.type === 'hack-terminals') timers.push({ segmentId: seg.id, type: c.type, seconds: c.secondsPerTerminal * c.terminalMarkerIds.length });
    else if (c.type === 'timed-rescue') timers.push({ segmentId: seg.id, type: c.type, seconds: c.seconds });
    else if (c.type === 'defense-waves') timers.push({ segmentId: seg.id, type: c.type, seconds: c.waveIntervalSeconds });
  }
}

describe('combat balance — measurement + sanity bounds', () => {
  it('every non-boss enemy dies in a reasonable window at the reference DPS', () => {
    for (const e of nonBoss) {
      const t = ttk(baseEffectiveHp(e.maxHp, e.maxShield));
      expect(t, `${e.id} TTK=${t}s`).toBeGreaterThanOrEqual(1);
      expect(t, `${e.id} TTK=${t}s`).toBeLessThanOrEqual(15);
    }
  });

  it('affix density is bounded and escalates with campaign depth', () => {
    for (const [zone, d] of Object.entries(zoneDensity)) expect(d, zone).toBeLessThanOrEqual(0.6);
    expect(zoneDensity['zone_rescue_vanguard_finale'] ?? 0).toBeGreaterThan(zoneDensity['zone_downtown_traffic_collapse'] ?? 1);
  });

  it('every objective timer is in a sane range', () => {
    for (const t of timers) {
      expect(t.seconds, `${t.segmentId}/${t.type}`).toBeGreaterThanOrEqual(3);
      expect(t.seconds, `${t.segmentId}/${t.type}`).toBeLessThanOrEqual(60);
    }
  });

  it('writes the balance report', () => {
    const md = buildReport();
    try {
      writeFileSync(resolve(process.cwd(), 'docs/combat_balance_report.md'), md, 'utf8');
    } catch {
      // Read-only FS (CI) — the assertions above already validated the numbers; skip the write silently.
    }
    expect(md.length).toBeGreaterThan(500);
  });
});

function buildReport(): string {
  const L: string[] = [];
  L.push('# Combat Balance Report (auto-generated)');
  L.push('');
  L.push('> Generated by `src/game/combat/combatBalance.report.test.ts` from the live seed data. Do NOT hand-edit —');
  L.push('> re-run `npx vitest run combatBalance.report` to refresh. This is a MEASUREMENT pass: no balance');
  L.push(`> constants were changed. Reference DPS = **${REFERENCE_DPS}** (a yardstick to turn HP into time-to-kill, not a tuning knob).`);
  L.push('');

  L.push('## 1. Enemy effective HP & time-to-kill');
  L.push('');
  L.push('| Enemy | maxHp | shield | base effHP | TTK @ref | TTK ng-plus (HP ×' + enemyHpMult('ng-plus') + ') |');
  L.push('|---|--:|--:|--:|--:|--:|');
  for (const e of SEED_ENEMIES) {
    const base = baseEffectiveHp(e.maxHp, e.maxShield);
    const ng = e.maxHp * enemyHpMult('ng-plus') + (e.maxShield ?? 0);
    L.push(`| ${e.isBoss ? '**' + e.id + '** (boss)' : e.id} | ${e.maxHp} | ${e.maxShield ?? 0} | ${base} | ${ttk(base)}s | ${ttk(ng)}s |`);
  }
  L.push('');
  L.push('_Note: `hard` does not scale enemy HP (only incoming player damage ×1.4); only `ng-plus` scales enemy HP (×' + enemyHpMult('ng-plus') + ')._');
  L.push('');

  L.push('## 2. Elite affix effective-HP multipliers');
  L.push('');
  L.push('Shows how much tankier a given affix makes a LOW-HP enemy (`zip_glitch`, 45 HP) vs a HIGH-HP one (`quake_walker`, 160 HP). `shielded` now uses a %-of-maxHp shield so the multiplier is consistent across HP tiers (previously a flat +60 over-tanked low-HP enemies).');
  L.push('');
  L.push('| Affix | hpMult | shield | zip ×effHP | quake ×effHP | other effects |');
  L.push('|---|--:|--:|--:|--:|---|');
  const zip = SEED_ENEMIES.find((e) => e.id === 'zip_glitch')!;
  const quake = SEED_ENEMIES.find((e) => e.id === 'quake_walker')!;
  for (const a of SEED_ELITE_AFFIXES) {
    const zr = (affixEffectiveHp(zip.maxHp, zip.maxShield, a) / baseEffectiveHp(zip.maxHp, zip.maxShield)).toFixed(2);
    const qr = (affixEffectiveHp(quake.maxHp, quake.maxShield, a) / baseEffectiveHp(quake.maxHp, quake.maxShield)).toFixed(2);
    const fx: string[] = [];
    if (a.speedMult) fx.push(`speed ×${a.speedMult}`);
    if (a.regenPerSec) fx.push(`regen ${a.regenPerSec}/s`);
    if (a.lifestealFraction) fx.push(`lifesteal ${a.lifestealFraction * 100}%`);
    if (a.onDeathExplosion) fx.push(`death boom ${a.onDeathExplosion.damage}@${a.onDeathExplosion.radius}m`);
    if (a.berserk) fx.push(`<${a.berserk.hpThreshold * 100}% HP → speed ×${a.berserk.speedMult}`);
    if (a.onDeathSummon) fx.push(`summon ${a.onDeathSummon.count}×${a.onDeathSummon.enemyId}`);
    const shieldCol = a.shieldFraction ? `${a.shieldFraction * 100}%HP` : `${a.addShield ?? 0}`;
    L.push(`| ${a.id} | ${a.hpMult ?? 1} | ${shieldCol} | ${zr}× | ${qr}× | ${fx.join(', ') || '—'} |`);
  }
  L.push('');

  L.push('## 3. Affix density per zone (measured from applied policies)');
  L.push('');
  L.push('| Zone | max chancePerEnemy |');
  L.push('|---|--:|');
  for (const [z, d] of Object.entries(zoneDensity).sort((a, b) => a[1] - b[1])) L.push(`| ${z} | ${d} |`);
  L.push('');

  L.push('## 4. Objective timers');
  L.push('');
  L.push('| Segment | type | seconds |');
  L.push('|---|---|--:|');
  for (const t of timers.sort((a, b) => a.type.localeCompare(b.type))) L.push(`| ${t.segmentId} | ${t.type} | ${t.seconds} |`);
  L.push('');

  L.push('## 5. Element-reaction burst damage');
  L.push('');
  L.push('| Reaction | primary → trigger | bonus dmg | AoE | consumes primary |');
  L.push('|---|---|--:|--:|:--:|');
  for (const r of SEED_ELEMENT_REACTIONS) {
    L.push(`| ${r.reaction}${r.enabled === false ? ' _(off)_' : ''} | ${r.primaryStatus} → ${r.triggerStatus} | ${r.bonusDamage} | ${r.aoeRadius ? r.aoeRadius + 'm' : '—'} | ${r.consumesPrimary ? 'yes' : 'no'} |`);
  }
  L.push('');

  L.push('## 6. Balance-pass changes applied + still flagged for human feel-check');
  L.push('');
  L.push('**Applied (conservative, data-driven):**');
  L.push('- ✅ **`shielded`** flat +60 shield → **45%-of-maxHp** shield, so its effective-HP boost is consistent across HP tiers (see §2 — zip and quake now match).');
  L.push('- ✅ **`swift`** move speed ×1.5 → **×1.35** (less frustrating to chase).');
  L.push('- ✅ **`conduct`** AoE radius 8 → **6 m** + cooldown 700 → **1000 ms** so the no-consume chain can\'t re-trigger as fast.');
  L.push('- ✅ **Early-zone affix density** floor raised (downtown 0.15 → **0.20**, factory 0.20 → **0.22**) so early zones actually show affixes.');
  L.push('');
  L.push('**Still needs a real GPU feel pass:**');
  L.push('- The exact `shieldFraction` / `swift` values + the full density curve (finale 0.5 + max 2) — verify escalation feels right in motion.');
  L.push('- TTK uses a flat reference DPS; real hero DPS varies a lot by kit/upgrades/mods — the table is a relative sanity check, not absolute balance.');
  L.push('');
  return L.join('\n');
}
